spring:
  application:
    name: HelloServer

server:
  port: 8080

eureka:
  client:
    serviceUrl:
        defaultZone: ${EUREKA_URL:http://netflix-eureka.cloudapps.nocosetest.com/eureka/v2/}
    healthcheck:
      enabled: false
  instance:
    metadata:
    preferIpAddress: true
    instanceId: ${MY_POD_NAMESPACE}:${MY_POD_NAME}:${spring.application.instance_id}
    leaseRenewalIntervalInSeconds: 10


    #instanceId: ${spring.application.name}:${spring.application.instance_id}
    #    hostname: localhost
    #    nonSecurePort: 9090
#  password: ${EUREKA_USER_PASSWORD:password}
