spring:
  application:
    name: HelloServer

server:
  port: 8080

eureka:
  client:
    serviceUrl:
        defaultZone: ${EUREKA_URL:http://netflix-eureka.cloudapps.nocosetest.com/eureka/v2/}
    healthcheck:
      enabled: false
  instance:
    metadata:
#    nonSecurePort: 9090
    preferIpAddress: true
#    hostname: localhost
    instanceId: ${spring.application.name}:${spring.application.instance_id}
#  password: ${EUREKA_USER_PASSWORD:password}
