spring:
  application:
    name: HelloClient

server:
  port: 8080

eureka:
  client:
    serviceUrl:
        defaultZone: ${EUREKA_URL:http://netflix-eureka.cloudapps.nocosetest.com/eureka/v2/}
    healthcheck:
      enabled: true
  instance:
      preferIpAddress: true
      leaseRenewalIntervalInSeconds: 10
      instanceId: ${MY_POD_NAMESPACE}:${MY_POD_NAME}:${spring.application.instance_id}
#      metadataMap:
#          instanceId: ${spring.application.name}:${spring.application.instance_id}



endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false